### ISSUE TITLE
get-list endpoint returns incorrect URLs

### ISSUE THREAD

**Issue by wesbos** [ClearskyApp06/clearskyservices#1]
Using the get-lists API endpoint, for example https://api.clearsky.services/api/v1/anon/get-list/wesbos.com

returns mostly broken urls, such as https://bsky.app/profile/did:plc:2ptby2khuvcyyli5fmjywfmc/lists/3lahp3zhqem2j

I have tracked it down to the list ID at the end being slightly different. 

For example the list above's correct URL is https://bsky.app/profile/benseymour.com/lists/3lahp3zhkj42j

3lahp3zh**qem2j**
3lahp3zh**kj42j**

Do these IDs change when they are update on bsky?

Also as a side note, many of these lists are starter-packs, and then the URLs are also incorrect in a second way as they should point towards `https://bsky.app/starter-pack/$HANDLE/$ID`

**Comment by thieflord06** [comment]
I will investigate the changes in the new format for the URIs and add the scheme for starter packs. 

DID was being used so that the handle didn't matter but I guess they change the way that works too.

**Comment by thieflord06** [comment]
Started tracking starter packs. We will have to recrawl the network to get all of them, that will take a while.

A new API specifically for starter packs will be coming soon.

**Comment by jakebailey** [comment]
I noticed this too; my workaround has been to just use `https://public.api.bsky.app/xrpc/app.bsky.graph.getLists?actor=<did>`, then search for the list which has the same name, which seems to work for every list I try to find, at the cost of more API calls.

(The tool I wrote doesn't use starter packs, but, I assume it would also work to use `https://public.api.bsky.app/xrpc/app.bsky.graph.getActorStarterPacks?actor=<did>` and do the same thing.

**Comment by thieflord06** [comment]
I found the issue:

The URL was being built wrong. I will add in a temporary fix that rebuilds the URL on the fly until they are all fixed in the db.

**Comment by thieflord06** [comment]
The endpoint has been updated, correctly formatted URLs are now being returned.

**Comment by thieflord06** [comment]
We are still working to convert all lists that are starter pack over to explicit starter pack records. An endpoint for that will be published soon. I'm going to close this as the main issue is resolved.
